sudo: false
language: clojure
lein: 2.8.1
jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11

env:
  global:
    # CLOJARS_USERNAME
    - secure: "FBu3XKrJw757i9AcAZz49wH4wDeWtCclZC9IrIEZNXjr/I8uf3WYs/o+WXZF0DtkVX6S0u+9liPupcRATthJDVBTfri1ZyI+iTlkd+SxFU8dASgzpzlBNEXsY/23qZ43BjdqIhOJaJxwAiiLpsJ3EKOYnCDx1108ZE63YVxgvUlDqT8WBUmvY058fHLiYbU9nVosMCU7MAVohd9Cw6RSXxvDOtg3uHwV3OEe1lrFtiMWBDH+wYm3s4w+01PMDs0z+b0ar/ZENSHNeUfBV0uR/+z+NqazAxNg+uSqLCAqTF7HGabtNoptGDOJAScsQdOKPrNw1dQ/Jl+wi1xWbteLfgG/eebI5C0jm22oyy42ymuTP7eZ1H6FYWNX5Vl9ZXw+9hWHzTEOH9By43XyCxwkOFrgfZuf8DuhvJr7LvgAUvhM6A/rn+A2Pm5ykOUknRGU7PhX/42OoVU/vCHcFnl4QJZqLCDOtRO4G9+jmUVAjAtLq/1y/+gsQQh3piIoGVVow8VDgmdtIlwhvKFxZp3LEmrJfNsXwWn88KLQXo1NljA6hrPD0vDuSGZVez89IwBZ4bnGUiYeHOkzf9YGnnIuOGy6aqUiNVZVXVMYxxbnUElMsPbmIvFTp/fZuDMhH9+wciVddoTpT1z7U/0ly5XnAAUy13VWT8EiBmeL4G9n6+o="
    # CLOJARS_PASSWORD
    - secure: "GiVKD9EMjwW6CkQwF1rwvJqlhwSLICfHvY3Exp/fJYFs468mk2LBl7VM8EG78wXoqxXRHHCPdhm1X5db5Lj13aTS7TDJbWL0i4srlYDFs6kfnkltROutGumgEproEeo7pA8Oix5wCqcEIlK3GDldWFIdHxkbj9wqWWsQ2GQxr0K3EVB5SuBp6bwAv9kXDBYrjOmrpQuP5uc4DqYYw34gz2ptAca2u5mSh1EitC2iPUCZDSw5cd4/YpiSFx2uo1L5YWQAHIBq+VnpLVCG3iypzDLJEhJrbF6qiAO3YTdgTIpBXf1vRJUjNZ0WoUPFRputp1tJpZcebOyBPgxlgsGS/MoBVxUk7rlFl6iJvp6L89WOxE5OX2+rG4nYRuraqbYLz+j0myCRU9PKvWQmraqARg8zONyGtuFE8StqFQ5ykGQHUg4vFKzuvjRyaIl+OWvDGRlVjZo4AE0TD61r+2x5wJbi7FKwtsk5XfXNF+X3ntL7fsvCRjj2tjQUJyWs2rBQCsDnYVs0n///J+qhluR/MXs+Zda4j/EjqPyCnKLAPUegHWGY42hgLbUWDAV9+U70cnzbnG+PUGT2vqvR6czX3iVHjGFnT7bCLk6RPmYteaF7ywgVHA7WlzEHpp/7rT86Khga0foIdf3ScWp71Xzw7Kh+V5mR8tG2LvbX95VSIG8="
    # GITHUB_TOKEN
    - secure: "J65dl520kW0eLm7zhhzyYcmNDnma0JSbtXEExDALHAzC98S/QlMj1DmnAGpGU+3bv8CscEheKoUpyu7anw1NUSr/fkJmeCo6b4OzK5PuUDA2abXvfSVHtHKZFYLbcFepg+bxYM24XQdVTIiGpPvtrP2eZFTfAi1y2jbCzDjxg7WEWHOt8U8WcxUdRkWtcnzXLsBIUKRKqqYUgCA1A69WvwjseiM+qEcvlaJqnrPGE0hdB21XjtiqShfdD4fREmJbvohytI9bJn4sjgQhr9awD/WseDmQWJocJbiI3wbjbfxTXdmYi1AkhZxO9guwv//zvWvJbytEK/5jlvN4dUyFPb1g/ekh12kmv6K0T5YmmRQU0PJRGBLT+BQiKCegfpmBxpGe1TZuKdWypXgPTdTUczPrcGh927IPUkgsu6vKP56mvvgBHWieLT7qaCzsdg20PoPNk1gJz7qY1IT3enHQGAxxApCkjbMnF9tvbqftZlGTPQvPPAhq2C8Gwxv0keWImBg4pxhzg8INhc7K8OXe67PDObQt/8uNPXc5yxJGejGmBKDrpebTK4sHbnlqxZ3GjszUtxluXwwnde7P61YIHbprMdugrKjWS/yHgxNLttO+CVvjurhJ2LqHbQPVD6pnlCpwyMLJf4mu4tQENcje5Opwj1m9lIsi40qHIVrPnVU="

script:
  - export PROFILES=+1.6:+1.7:+1.8:+1.9
  - if [[ $JAVA_HOME != *java-7* ]]; then export PROFILES=${PROFILES}:+1.10; fi
  - lein with-profile ${PROFILES} do version, check, test

deploy:
  # Deploy binaries to Clojars
  - provider: script
    skip_cleanup: true
    script: lein deploy
    on:
      branch: master
      jdk: oraclejdk11
  # Generate documentation
  - provider: script
    skip_cleanup: true
    script: lein codox
    on:
      branch: master
      jdk: oraclejdk11
  # Deploy documentation
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    email: pmonks+travisci@gmail.com
    name: Travis CI - pmonks
    local_dir: target/doc
    on:
      branch: master
      jdk: oraclejdk11
