sudo: false
language: clojure
lein: 2.8.1
dist: trusty   # Because Travis CI's support for older versions of Java on newer distros is *garbage*
jdk:
  - openjdk7
  - oraclejdk8
#  - oraclejdk9   # Removed as it slows down the build and is poorly supported by Travis CI
#  - openjdk10    # Removed as it slows down the build and is poorly supported by Travis CI
  - openjdk11     # Don't fall for Oracle's trick: https://blog.joda.org/2018/09/do-not-fall-into-oracles-java-11-trap.html

env:
  global:
    # CLOJARS_USERNAME
    - secure: "FBu3XKrJw757i9AcAZz49wH4wDeWtCclZC9IrIEZNXjr/I8uf3WYs/o+WXZF0DtkVX6S0u+9liPupcRATthJDVBTfri1ZyI+iTlkd+SxFU8dASgzpzlBNEXsY/23qZ43BjdqIhOJaJxwAiiLpsJ3EKOYnCDx1108ZE63YVxgvUlDqT8WBUmvY058fHLiYbU9nVosMCU7MAVohd9Cw6RSXxvDOtg3uHwV3OEe1lrFtiMWBDH+wYm3s4w+01PMDs0z+b0ar/ZENSHNeUfBV0uR/+z+NqazAxNg+uSqLCAqTF7HGabtNoptGDOJAScsQdOKPrNw1dQ/Jl+wi1xWbteLfgG/eebI5C0jm22oyy42ymuTP7eZ1H6FYWNX5Vl9ZXw+9hWHzTEOH9By43XyCxwkOFrgfZuf8DuhvJr7LvgAUvhM6A/rn+A2Pm5ykOUknRGU7PhX/42OoVU/vCHcFnl4QJZqLCDOtRO4G9+jmUVAjAtLq/1y/+gsQQh3piIoGVVow8VDgmdtIlwhvKFxZp3LEmrJfNsXwWn88KLQXo1NljA6hrPD0vDuSGZVez89IwBZ4bnGUiYeHOkzf9YGnnIuOGy6aqUiNVZVXVMYxxbnUElMsPbmIvFTp/fZuDMhH9+wciVddoTpT1z7U/0ly5XnAAUy13VWT8EiBmeL4G9n6+o="
    # CLOJARS_PASSWORD (actually a Clojars token, after 2020 changes to Clojars' security model)
    - secure: "NV8g0q43yMGgWfWzxOvl6hLhRW0JUWvFkmRhxZGcK12pavqltfvHLpxCBjKEP4wkyv6njEsSB7kylc58myxZq8JtqAhocbhcjq3gk82ORYDh5uaeAIlS7CcRJP4qtHGPhCGchgBB7ZyiFWaUOai5mOqeV/iXmuzfjC+jzN6t+24IWQfTJVfs31eYtChZ1G+lLjh0FC6rlS1Wpzlpv22X+AV2h9j6yiPaFhdDOvLoPRMGlS1RNSK7ZZUPmHB9Yuyljgh17KXOYmfm8PatkhWENWaIu44StliDnD1lGVtVUzloK8GPufICCLb5UkHFrcDE7Dh6xoNRbyoLridT+DE2bL32gbfXLziakhodAfa2NkoY9k/jQBJngNnyL1gQLiNsYbNNSNF7vaBwSIycl4Jpp6zIxCKtl+/tA0lDKUw+ydOb/ZSrneilqTFKD8hnaRTxTqZMqyTLau8vMocaMx0yDLApovVk+mxpRzV016g30zJKtHXUrjQuPnXESu0kjfEFFUMk7c6SLxug1WfyEWOr+P+ltMljINDwRUyFevZHXlSoo2dirNOwXYGlh6BlOiCYhs5RN5+yWjGNqwioa5yDyKu/MzcgtZi5sz2jf8JQXOjYwps2scId9qONh4nA9LCdCX8MUzZ7/Hy51y2MI+6KR0aDzyrLpOs4kGUBJNppWFQ="
    # GITHUB_TOKEN
    - secure: "J65dl520kW0eLm7zhhzyYcmNDnma0JSbtXEExDALHAzC98S/QlMj1DmnAGpGU+3bv8CscEheKoUpyu7anw1NUSr/fkJmeCo6b4OzK5PuUDA2abXvfSVHtHKZFYLbcFepg+bxYM24XQdVTIiGpPvtrP2eZFTfAi1y2jbCzDjxg7WEWHOt8U8WcxUdRkWtcnzXLsBIUKRKqqYUgCA1A69WvwjseiM+qEcvlaJqnrPGE0hdB21XjtiqShfdD4fREmJbvohytI9bJn4sjgQhr9awD/WseDmQWJocJbiI3wbjbfxTXdmYi1AkhZxO9guwv//zvWvJbytEK/5jlvN4dUyFPb1g/ekh12kmv6K0T5YmmRQU0PJRGBLT+BQiKCegfpmBxpGe1TZuKdWypXgPTdTUczPrcGh927IPUkgsu6vKP56mvvgBHWieLT7qaCzsdg20PoPNk1gJz7qY1IT3enHQGAxxApCkjbMnF9tvbqftZlGTPQvPPAhq2C8Gwxv0keWImBg4pxhzg8INhc7K8OXe67PDObQt/8uNPXc5yxJGejGmBKDrpebTK4sHbnlqxZ3GjszUtxluXwwnde7P61YIHbprMdugrKjWS/yHgxNLttO+CVvjurhJ2LqHbQPVD6pnlCpwyMLJf4mu4tQENcje5Opwj1m9lIsi40qHIVrPnVU="

before_install:
  # Workaround for TravisCI's garbage openjdk10 base image
  - if [[ $JAVA_HOME == *openjdk10* ]]; then rm "${JAVA_HOME}/lib/security/cacerts"; ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"; fi

script:
  - export PROFILES=+1.7:+1.8:+1.9
  - if [[ $JAVA_HOME != *java-7* ]]; then export PROFILES=${PROFILES}:+1.10; fi
  - lein with-profile ${PROFILES} do version, check, test

deploy:
  # Deploy binaries to Clojars
  - provider: script
    skip_cleanup: true
    script: lein deploy
    on:
      branch: master
      jdk: openjdk11
  # Generate documentation
  - provider: script
    skip_cleanup: true
    script: lein codox
    on:
      branch: master
      jdk: openjdk11
  # Deploy documentation
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    email: pmonks+travisci@gmail.com
    name: Travis CI - pmonks
    local_dir: target/doc
    on:
      branch: master
      jdk: openjdk11
